### ISSUE TITLE
Interrupted download

### ISSUE THREAD

**Issue by just-another-random-person** [KunaiFire/rechat-dl#2]
One download kept failing at random chunks (46/248, 115/248, 185/248) with the following error:

`downloading chunk 185 / 248got an error in chat message response: {u'errors': [{u'status': 500, u'detail': u'[503] {"error":"ReduceSearchPhaseException[Failed to execute phase [fetch], [reduce] ]; nested: EsRejectedExecutionException[rejected execution (queue capacity 1000) on org.elasticsearch.action.search.type.TransportSearchQueryThenFetchAction$AsyncAction$2@4ea78e3a]; ","status":503}'}]}`

Managed to download it after about 100 (!) tries.

Is there a way to have it retry/resume automatically upon such errors?
Or an unattended way to do this?

Thanks.

**Comment by makamys** [comment]
I think that error means Twitch's servers were overloaded at the time. I didn't make the script retry on errors received in json because I thought they were always permanent ones like "the vod has expired", where no amount of retrying would solve the problem. But I made it retry now that I know they can be temporary, so thanks for making the issue.

About the 100 retry thing, currently the retry attempt count is hardcoded at 6, so I'll add an option to set the amount of retries. I'll do it later though because it would require rewriting the argument handler code. For the time being you can change the line

``` python
CHUNK_ATTEMPTS = 6
```

to a higher number to make it retry more often, if you still get errors.

**Comment by just-another-random-person** [comment]
Thanks so much for the quick response. <3
